<?xml version="1.0" ?>

<robot name="vehicle" xmlns:xacro="http://www.ros.org/wiki/xacro">
    
    <xacro:macro name="vehicle_wheels" params="parent">

        <link name="rear_right_wheel">
            <visual>
                <origin xyz="0 0 0"/>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
                </geometry>
                <material name="black"/>
            </visual>

            <collision>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
                </geometry>
            </collision>

            <xacro:cylinder_inertia mass="${wheel_mass}" r="${wheel_radius}" h="${wheel_length}"/>
        </link>

         <link name="rear_left_wheel">
            <visual>
                <origin xyz="0 0 0"/>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
                </geometry>
                <material name="black"/>
            </visual>

            <collision>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
                </geometry>
            </collision>

            <xacro:cylinder_inertia mass="${wheel_mass}" r="${wheel_radius}" h="${wheel_length}"/>
        </link>

         <link name="front_caster_wheel">
            <visual>
                <origin xyz="0 0 0"/>
                <geometry>
                    <sphere radius="${caster_wheel_radius}"/>
                </geometry>
                <material name="black"/>
            </visual>

            <collision>
                <origin xyz="0 0 0"/>
                <geometry>
                    <sphere radius="${caster_wheel_radius}"/>
                </geometry>
            </collision>

            <xacro:sphere_inertia mass="${caster_wheel_mass}" r="${caster_wheel_radius}" />
        </link>

        <joint name="rear_right_wheel_joint" type="continuous">
            <parent link="${parent}"/>
            <child link="rear_right_wheel"/>
            <origin xyz="${-(body_width / 4)} ${-((body_depth / 2) + (wheel_length / 2))} ${-wheel_zoff}" rpy="-${pi/2} 0 0"/>
            <axis xyz="0 0 1"/>
            <!-- <dynamics damping="0.2" /> -->
        </joint>

        <joint name="rear_left_wheel_joint" type="continuous">
            <parent link="${parent}"/>
            <child link="rear_left_wheel"/>
            <origin xyz="${-(body_width / 4)} ${((body_depth / 2) + (wheel_length / 2))} ${-wheel_zoff}" rpy="-${pi/2} 0 0"/>
            <axis xyz="0 0 1"/>
            <!-- <dynamics damping="0.2" /> -->
        </joint>

        <joint name="front_caster_wheel_joint" type="fixed">
            <parent link="${parent}"/>
            <child  link="front_caster_wheel"/>
            <origin xyz="${body_width / 4} 0 ${-wheel_zoff}"/>
        </joint>

    </xacro:macro>


</robot>