<?xml version="1.0"?>

<robot name="vehicle" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:arg name="is_ignition" default="true" />
    <xacro:include filename="$(find vehicle_description)/urdf/includes.xacro" />
   
    <xacro:vehicle_body />
    <xacro:vehicle_wheels parent="vehicle_body"/>
            
    <xacro:imu_sensor name="imu1" topic_ns="imu1" parent="vehicle_body">
        <origin xyz="0.05 0 ${(body_height / 2) + wheel_radius}" rpy="-${pi/2} 0 0"/>
    </xacro:imu_sensor>
    <xacro:imu_sensor name="imu2" topic_ns="imu2" parent="vehicle_body">
        <origin xyz="0 0 ${(body_height / 2) + wheel_radius}" rpy="-${pi/2} 0 0"></origin>
    </xacro:imu_sensor>
    <xacro:imu_sensor name="imu3" topic_ns="imu3" parent="vehicle_body">
        <origin xyz="-0.05 0 ${(body_height / 2) + wheel_radius}" rpy="-${pi/2} 0 0"></origin>
    </xacro:imu_sensor>
    
</robot>