<?xml version="1.0" ?>

<robot name="vehicle" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:arg name="is_ignition" default="true" />
    <xacro:include filename="$(find vehicle_description)/urdf/includes.xacro" />
   
    <xacro:vehicle_body />
    <xacro:vehicle_wheels parent="base_link"/>
            
    <xacro:imu_sensor sensor_type="vn_100" name="imu1" topic_ns="imu1" parent="base_link">
        <origin xyz="0 0 ${(body_height / 2) + 0.0015 + wheel_radius}" rpy="0 0 0"/>
    </xacro:imu_sensor>
    <xacro:imu_sensor sensor_type="vn_100" name="imu2" topic_ns="imu2" parent="base_link">
        <origin xyz="0 0 ${(body_height / 2) + 0.0015 + wheel_radius}" rpy="0 0 0"/>
    </xacro:imu_sensor>
    <xacro:imu_sensor sensor_type="vn_100" name="imu3" topic_ns="imu3" parent="base_link">
        <origin xyz="0 0 ${(body_height / 2) + 0.0015 + wheel_radius}" rpy="0 0 0"/>
    </xacro:imu_sensor>
    <xacro:navsat_sensor name="gps" topic_ns="navsat" parent="base_link" >
        <origin xyz="0.1 0 ${(body_height / 2) + 0.005 + wheel_radius}" rpy="0 0 0" />
    </xacro:navsat_sensor>

</robot>