<?xml version="1.0" ?>

<robot name="vehicle" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- Vehicle Body Parameters -->
    <xacro:property name="body_width"  value="0.3" />
    <xacro:property name="body_depth"  value="0.25" />
    <xacro:property name="body_height" value="0.1" />
    <xacro:property name="body_mass" value="3" />

    <!-- WHEEL PROPERTIES-->
    <xacro:property name="wheel_radius" value="0.05"/>
    <xacro:property name="wheel_length" value="0.05" />
    <xacro:property name="wheel_mass" value="0.5" /> 
    <xacro:property name="caster_wheel_radius" value="0.05" />
    <xacro:property name="caster_wheel_mass" value="0.5"/>

    <xacro:macro name="vehicle_body">
    
        <link name="base_footprint" />
        <link name="vehicle_body">
            <visual>
                <origin xyz ="0 0 ${wheel_radius}" />
                <geometry>
                    <box size="${body_width} ${body_depth} ${body_height}"/>
                </geometry>
                <material name="red"/>
            </visual>
                
            <collision>
                <origin xyz ="0 0 ${wheel_radius}" />
                <geometry>
                    <box size="${body_width} ${body_depth} ${body_height}"/>
                </geometry>
            </collision>

            <xacro:solid_cuboid_inertia mass="${body_mass}" x="${body_width}" y="${body_depth}" z="${body_height}" />
        </link>

        <joint name="vehicle_body_joint" type="fixed">
            <parent link="base_footprint"/>
            <child link="vehicle_body" />
            <origin xyz="0 0 ${body_height / 2}"/>
        </joint>

    </xacro:macro>

</robot>